version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "cool"
      MYSQL_USER: "cool"
      MYSQL_PASSWORD: "123123"
  redis:
    image: redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/:/data/
  soruxgpt-claude-share-server:
    image: epicmo/claude-share-server:latest
    restart: always
    ports:
      - 8300:8001
    environment:
      TZ: Asia/Shanghai
      CHATPROXY: "此处填写你的网关地址"
      AUTHKEY: "此处填写你的网关 KEY"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/soruxgpt-claude-share-server/:/app/data/
    labels:
      - "com.centurylinklabs.watchtower.scope=epicmo-claude-share-server"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope epicmo-claude-share-server --cleanup
    restart: always
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.scope=epicmo-claude-share-server"